_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

accelerator: auto
devices: 4

limit_val_batches: 100
limit_test_batches: 100
val_check_interval: 300

enable_progress_bar: False